update

upgrade

install bash
install ack
install git
install htop
install rbenv
install redis
install memcached
install node
install imagemagick
install ffmpeg
install nginx
install readline
install tree
install tmux
install elasticsearch
install postgresql

tap homebrew/versions

cleanup
