update

upgrade

install bash
install ack
install git
install htop
install ruby-build
install rbenv
install redis
install memcached
install node
install nginx
install readline
install postgresql

tap homebrew/versions

cleanup
